import AntDesignIcon from 'react-native-vector-icons/AntDesign';
import EntypoIcon from 'react-native-vector-icons/Entypo';
import EvilIconsIcon from 'react-native-vector-icons/EvilIcons';
import FeatherIcon from 'react-native-vector-icons/Feather';
import FontAwesomeIcon from 'react-native-vector-icons/FontAwesome';
import FontAwesome5Icon from 'react-native-vector-icons/FontAwesome5';
import FontAwesome6Icon from 'react-native-vector-icons/FontAwesome6';
import FontAwesome5ProIcon from 'react-native-vector-icons/FontAwesome5Pro';
import FontAwesome6ProIcon from 'react-native-vector-icons/FontAwesome6Pro';
import FontistoIcon from 'react-native-vector-icons/Fontisto';
import FoundationIcon from 'react-native-vector-icons/Foundation';
import IoniconsIcon from 'react-native-vector-icons/Ionicons';
import MaterialCommunityIconsIcon from 'react-native-vector-icons/MaterialCommunityIcons';
import MaterialIconsIcon from 'react-native-vector-icons/MaterialIcons';

export const AntDesign = AntDesignIcon;
export const Entypo = EntypoIcon;
export const EvilIcons = EvilIconsIcon;
export const Feather = FeatherIcon;
export const FontAwesome = FontAwesomeIcon;
export const FontAwesome5 = FontAwesome5Icon;
export const FontAwesome6 = FontAwesome6Icon;
export const FontAwesome5Pro = FontAwesome5ProIcon;
export const FontAwesome6Pro = FontAwesome6ProIcon;
export const Fontisto = FontistoIcon;
export const Foundation = FoundationIcon;
export const Ionicons = IoniconsIcon;
export const MaterialCommunityIcons = MaterialCommunityIconsIcon;
export const MaterialIcons = MaterialIconsIcon;
